# Copyright 2004 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

# Makeit Initialisation.

MODULES = cxx ose

include makeit/setup.mk

# Module Initialisation/Definitions.

PROGRAMS += _ValidatorService

include makeit/modules.mk

# Additional Dependencies/Rules.

mostlyclean.always ::
	$(RM) *.pyc
