# GENERATED FILE, DO NOT EDIT.

OBJECTS1 = \
 hash_32.obj \
 hash_32a.obj \
 hash_64.obj \
 hash_64a.obj \
 regcomp.obj \
 regerror.obj \
 regexec.obj \
 regfree.obj \


OBJECTS2 = \
 otcanchor.obj \
 otcapplcatr.obj \
 otcavlhnode.obj \
 otcavllnode.obj \
 otcavlnode.obj \
 otcavltnode.obj \
 otcavltree.obj \
 otcbitset.obj \
 otccbitset.obj \
 otcdequei.obj \
 otchashntry.obj \
 otchashtble.obj \
 otciilink.obj \
 otcilink.obj \
 otcivlink.obj \
 otclink.obj \
 otclinkable.obj \
 otclinkcurs.obj \
 otclinkiter.obj \
 otclinklist.obj \
 otclisti.obj \
 otcrange.obj \
 otcrlink.obj \
 otcrngecurs.obj \
 otcvlink.obj \
 otcasrtfail.obj \
 otcassert.obj \
 otcensure.obj \
 otcerrors.obj \
 otcexcption.obj \
 otclogbuf.obj \
 otclogger.obj \
 otclogstrm.obj \
 otcnewhndlr.obj \
 otcoutofmem.obj \
 otcprecfail.obj \
 otcstophere.obj \
 otctermfunc.obj \
 otctobject.obj \
 otctracer.obj \
 otctracetag.obj \
 otctrcebuf.obj \
 otctrcestrm.obj \
 otctrcswtch.obj \
 otcwarning.obj \
 otcaction.obj \
 otcalarm.obj \
 otccondtion.obj \
 otcdispatch.obj \
 otcenvelope.obj \
 otcevagent.obj \
 otcevcllbck.obj \
 otcevent.obj \
 otceventjob.obj \
 otcevhandle.obj \
 otcevthread.obj \
 otcfailure.obj \
 otcfnagent.obj \
 otcgrpannc.obj \
 otcioevent.obj \
 otcjob.obj \
 otcjoblist.obj \
 otcjobqueue.obj \
 otcmessage.obj \
 otcopaque.obj \
 otcpbntftcn.obj \
 otcplreader.obj \
 otcreceiver.obj \
 otcreport.obj \
 otcrequest.obj \
 otcresponse.obj \
 otcropyload.obj \
 otcrwpyload.obj \
 otcsbscrptn.obj \
 otcservannc.obj \
 otcservbind.obj \
 otcshutdown.obj \
 otcsignal.obj \
 otcstartup.obj \
 otcsubject.obj \
 otcsvbroker.obj \
 otcsvpyload.obj \
 otcsvregsub.obj \
 otcsvrgstry.obj \
 otctimeout.obj \
 otcechosrvl.obj \
 otcfilesrvl.obj \
 otcfilesrvr.obj \
 otchttpdaem.obj \
 otchttplstn.obj \
 otchttpsrvl.obj \
 otchttpsrvr.obj \
 otchttpsssn.obj \
 otcrpcgtway.obj \
 otcrpcsrvlt.obj \
 otcxmlrpcgw.obj \
 otcxmlrpcsl.obj \
 otcalign.obj \
 otcarena.obj \
 otccluster.obj \
 otccmmnpool.obj \
 otcheap.obj \
 otcmcobject.obj \
 otcmpobject.obj \
 otcpool.obj \
 otccongest.obj \
 otcconnect.obj \
 otcendpoint.obj \
 otcepclient.obj \
 otcepintrfc.obj \
 otcepismesg.obj \
 otcepisockt.obj \
 otcepisstrm.obj \
 otcepisxxxx.obj \
 otceplisten.obj \
 otceprgstry.obj \
 otcepserver.obj \
 otcexchange.obj \
 otcexchannc.obj \
 otcexrgstry.obj \
 otcinetaddr.obj \
 otcinetclnt.obj \
 otcinetlstn.obj \
 otcinetsrvr.obj \
 otcunixaddr.obj \
 otcunixclnt.obj \
 otcunixlstn.obj \
 otcunixsrvr.obj \
 otccopy.obj \
 otcfuncbuf.obj \
 otcfuncstrm.obj \
 otchash.obj \
 otcrank.obj \
 otcvfuncbuf.obj \
 otccount.obj \
 otcrcount.obj \
 otcresource.obj \
 otcclckinfo.obj \
 otcdirectry.obj \
 otcpathname.obj \
 otcprogram.obj \
 otcsigblock.obj \
 otcsighndle.obj \
 otcstat.obj \
 otcstopwtch.obj \
 otccstring.obj \
 otcdomnode.obj \
 otcdomprpty.obj \
 otcdomstrng.obj \
 otcglobex.obj \
 otclstring.obj \
 otcoptions.obj \
 otcosstream.obj \
 otcpattern.obj \
 otcprprties.obj \
 otcrecord.obj \
 otcregex.obj \
 otcregexp.obj \
 otcrstring.obj \
 otcsilink.obj \
 otcslink.obj \
 otcslogger.obj \
 otcstring.obj \
 otcstrngbuf.obj \
 otcsvlink.obj \
 otcsymbol.obj \
 otctracepat.obj \
 otcvrecord.obj \
 otccvmutex.obj \
 otcmutex.obj \
 otcnrmutex.obj \
 otcrwmutex.obj \
 otctask.obj \
 otcdate.obj \
 otcduration.obj \
 otctime.obj \


OBJECTS3 = \
 onsactvrqst.obj \
 onsagent.obj \
 onscallback.obj \
 onscbobject.obj \
 onsexectecb.obj \
 onsmonitor.obj \
 onspndgcncl.obj \
 onspndgrspn.obj \
 onsservice.obj \


