## Copyright 2003-2004 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

## Initialisation.

SRCROOT := ..

MAKEIT_OPTIONS += suppress_workarea

include $(SRCROOT)/setup.mk

## Local definitions.

SUBDIRS := OSE OTC ONS

INCDIR := $(includedir)/$(PACKAGE_NAME)-$(PACKAGE_VERSION)

## Makeit modules.

include $(SRCROOT)/modules.mk
