# Copyright 1999-2004 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

# Makeit Initialisation.

MODULES = cxx ose

include makeit/setup.mk

# Module Initialisation/Definitions.

PROGRAMS += exchange-network
PROGRAMS += exchange

PROGRAMS += netrpc-gateway
PROGRAMS += xmlrpc-gateway

PROGRAMS += service

PROGRAMS += service-reports
PROGRAMS += service-request

include makeit/modules.mk

# Additional Dependencies/Rules.

