# Copyright 1999-2004 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

# Makeit Initialisation.

MODULES = cxx ose

include makeit/setup.mk

# Module Initialisation/Definitions.

PROGRAMS += read-client
PROGRAMS += write-client

PROGRAMS += daytime-server
PROGRAMS += echo-server
PROGRAMS += chargen-server

include makeit/modules.mk

# Additional Dependencies/Rules.

